site_name: continuous-control
repo_url: https://github.com/julionevadod/continuous-control
site_url: https://julionevadod.github.io/continuous-control
site_description: Project to train an agent to solve Reacher environment from Unity
site_author: Julio Nevado
edit_uri: edit/main/docs/
repo_name: julionevadod/continuous-control
copyright: Maintained by <a href="https://julionevadod.com">julionevadod</a>.

nav:
  - Home: index.md
  - Modules: modules.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: ["src/continuous_control"]
theme:
  name: material
  feature:
    tabs: true
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/julionevadod/continuous-control
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/continuous-control

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
